config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'



  resources :pets, only: [:index, :show] do
    resources :reservations, only: [:create]
  end

  resources :reservations, only: [:index]

  namespace :owner do
    resources :pets, only: [:index, :new, :create]
    resources :reservations, only: [:index] do
      member do
        patch 'accept'
        patch 'decline'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :photo , presence: true
  validates :name , presence: true
  validates :price_per_day , presence: true


  belongs_to :user
  has_one_attached :photo
  has_many :reservations, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # validates :photo , presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pets, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :phone_number, :city, :username, :address, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/owner/pets_controller.rb
class Owner::PetsController < ApplicationController
  def index
        @owner = current_user
        @mypets = @owner.pets
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render 'new'
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :description, :price_per_day, :photo)
  end


end

app/controllers/owner/reservations_controller.rb
class Owner::ReservationsController < ApplicationController

  def index
    @reservations = Reservation.joins(:pet).where(pets: { user: current_user })
  end

  def accept
   @reservation = Reservation.find(params[:id])
   @reservation.status = "Accepté"
   @reservation.save!
   redirect_to owner_reservations_path
  end

  def decline
   @reservation = Reservation.find(params[:id])
   @reservation.status = "Decliné"
   @reservation.save!
   redirect_to owner_reservations_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index


    @pets = Pet.geocoded # returns flats with coordinates
    @markers = @pets.map do |pet|
      {
        lat: pet.latitude,
        #lat: 48.0833,
        lng: pet.longitude,
        #lng: -1.6833,
        #infoWindow: render_to_string(partial: "info_window", locals: { mascot: mascot })
          #image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')   CUSTOM ICONE ON MAP
      }
    end
  end

  def show
    @pet = Pet.find(params[:id])
    @reservation = Reservation.new
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = current_user.reservations
  end



  def create
    @reservation = Reservation.new(reservation_params)
    @pet = Pet.find(params[:pet_id])
    @reservation.user = current_user
    @reservation.pet = @pet
    @reservation.total_price = (@reservation.end_date - @reservation.start_date)* @pet.price_per_day
    @reservation.status = 'en attente'

    if @reservation.save
      redirect_to reservations_path
    else
      redirect_to pets_path(@pet)
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
    # params.require(:reservation).permit(pet_id, user_id, :start_date, :end_date, :total_price, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/mascots/_info_window.html.erb
<h2><%= flat.name %></h2>
<p><%= flat.address %></p>

app/views/owner/pets/index.html.erb
<%= render 'shared/navbar' %>
    <!-- integration flash alerts devise -->
<%= render 'shared/flashes' %>

<div class="container">

  <h1 class="index-title pt-5">Voici la liste de vos mascottes</h1>

  <div class="cards">
    <% @mypets.each do |pet| %>
      <%= link_to pet_path(pet), class: 'no-deco' do %>
        <div class="card">
          <%= cl_image_tag(pet.photo.key) %>

          <div class="card-infos">
            <h2 class="pt-3 pet_name"> <%= pet.name %></h2>
            <h2 class="card-pricing pet_price"><strong> <%= pet.price_per_day %></strong>€/ jour</h2>
<!--             <h2 class="card-trip-pricing pet_price"><%= pet.user.username %></h2>
 -->            <%= cl_image_tag pet.user.photo.key, class: 'card-user avatar-bordered' %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/owner/pets/new.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="mt-5">Ajoute une nouvelle mascotte :</h1>
      <%= simple_form_for([:owner, @pet], remote: true) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :species %>
        <%= f.input :description %>
        <%= f.input :price_per_day %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Ajouter cette mascotte", class: "btn btn-primary" %>
      <% end %>


    </div>
  </div>
</div>

app/views/owner/pets/validate.html.erb
<%= render 'shared/navbar' %>

<h2>test avatar</h2>
<% @reservations.each do |reservation| %>
  <div class="reservation">

    <ul>
      <li>Nom : <%= reservation.pet.name %> </li>
      <li>Debut de la reservation : <%= reservation.start_date %> </li>
      <li>Fin de la reservation :  <%= reservation.end_date %> </li>
      <li>Prix Total <%= reservation.total_price %> €</li>
      <li>Statut : <%= reservation.status %> </li>
    </ul>
    <%= link_to "Accepter*", accept_owner_reservation_path, class:"btn btn-primary" %>
    <%= link_to "Decliner*", decline_owner_reservation_path, class:"btn btn-primary" %>
<% end %>

app/views/owner/reservations/index.html.erb
<%= render 'shared/navbar' %>

<div class="reservation container pt-5" >

  <h1 class="titre pt-5 pb-5">Mes demandes de réservation</h1>

  <% @reservations.each do |reservation| %>
    <div class="card-reservation pt-5">
      <%= cl_image_tag reservation.user.photo.key, class:'avatar-reservation'%>
      <ul>
        <li>Nom :<strong> <%= reservation.pet.name %> </strong></li>
        <li>Debut de la reservation : <%= reservation.start_date %> </li>
        <li>Fin de la reservation :  <%= reservation.end_date %> </li>
        <div class= "price">
        <li>Prix Total <%= reservation.total_price %> €</li>
        </div>
        <li>Statut : <%= reservation.status %> </li>
      <%= link_to "Accepter", accept_owner_reservation_path(reservation), method: :patch, class:"btn btn-success accept" %>
      <%= link_to "Decliner", decline_owner_reservation_path(reservation), method: :patch, class:"btn btn-danger decline" %>
      </ul>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="background">
  <div class="container center">
    <h1 class="title">Rent a pet</h1>
    <p class="content">Vous vous sentez vraiment seul pendant le confinemment ?<br>N'attendez pas !<br>Louez une mascotte pour la journée</p>
    <%= link_to "Louez", pets_path, class:"btn  button-home active"%>
  </div>
<!--   <p class="beware">* L'acteur ne peut être loué moins d'une journée.<br>Il sera à votre disposition pour faire le ménage, la cuisine ou garder les enfants.</p>
 --></div>

app/views/pets/index.html.erb
<%= render 'shared/navbar' %>
    <!-- integration flash alerts devise -->
<%= render 'shared/flashes' %>

 <h1 class="index-title pt-5">Choisissez votre partenaire de sortie</h1>

<div class="indexcontent pt-3">

  <div class="cards">

    <% @pets.each do |pet| %>

      <%= link_to pet_path(pet), class: 'no-deco' do %>

        <div class="card">
          <%= cl_image_tag(pet.photo.key) %>
          <div class="card-infos">
            <h2 class="pt-3 name"> <%= pet.name %></h2>
            <h2 class="card-pricing price"><strong> <%= pet.price_per_day %></strong>€/ jour</h2>
            <%= cl_image_tag pet.user.photo.key, class: 'card-user avatar-bordered' %>
          </div>
        </div>

      <% end %>

    <% end %>

  </div>
      <div id="map"
        style="width: 700px; height: 100vh"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
</div>

app/views/pets/show.html.erb
<%= render 'shared/navbar' %>
    <!-- integration flash alerts devise -->
<%= render 'shared/flashes' %>



<div class="container pt-5 ">
  <div class="place">
    <div class="card-product">
        <%= cl_image_tag(@pet.photo.key) %>
      <div class="card-product-infos">
        <h1 class="titre"><%= @pet.name %></h1>
        <div class="informations">
          <p><%= @pet.description %></p>
          <p class="pt-2">Adresse : <%= @pet.address %></p>
          <p class="pt-2">Espèce : <%= @pet.species %></p>
          <p class="prix pt-2"><strong><%= @pet.price_per_day %> € / jour</strong></p>
          <br>
          <div>
            <%= simple_form_for([@pet, @reservation], remote: true) do |f| %>
              <%= f.input :start_date, as: :date, html5: true, label: "Date de début" %>
              <%= f.input :end_date, as: :date, html5: true, label: "Date de début" %>
              <%= f.submit "Reservez*", class:"btn btn-primary resa" %>
            <% end %>
          </div>



          <br>
          <br>
          <br><br>
           <p class="ast">* L'acteur ne peut être loué moins d'une journée.<br>Il sera à votre disposition pour faire le ménage, la cuisine ou garder les enfants.</p>



        </div>
      </div>
    </div>


  </div>

</div>
<%= render 'shared/footer' %>

app/views/reservations/index.html.erb
<div>
<%= render 'shared/navbar' %>

</div>    <!-- integration flash alerts devise -->
<%= render 'shared/flashes' %>


    <!-- integration flash alerts devise -->

<div class="container pt-5">
  <div class="place">
    <h1 class="titre pt-3">Voici toutes vos locations </h1>

      <% @reservations.each do |reservation| %>
        <div class="container">

          <div class="container pt-3">
            <div class="card-reservation">
              <div class="col-4">
                <%= cl_image_tag(reservation.pet.photo.key) %>
              </div>
              <div class="col-8 ">
                <div>
                  <h4> <strong><%= reservation.pet.name %></strong> </h4>
                </div>
                <div>
                  <h6>Du  <%= reservation.start_date %> au <%= reservation.end_date %> </h6>
                </div>
                <div>
                  <h8>Statut : <%= reservation.status %> </h8>
                </div>
                <div class="price">
                  <h7>Prix Total <strong><%= reservation.total_price %> €</strong></h7>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Ce site Web a été fait avec le  <i class="fas fa-heart"></i>  à la Maison
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to pets_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/x750ln/image/upload/v1586254108/logo_d8abc3.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item active">
          <%= link_to "Toutes Mascottes", pets_path, class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Mes Mascottes", owner_pets_path, class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Mes locations", reservations_path, class: "nav-link" %>
        </li>




        <% if current_user.username == "hugo" %>

          <i class="fas fa-bell colorred"></i>
        <% end %>



        <li class="nav-item active">

          <%= link_to "mes reservations", owner_reservations_path, class: "nav-link" %>
        </li>


        <li class="nav-item">

          <%= link_to "Ajouter une mascotte", new_owner_pet_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <!-- <img src="paul.jpg" alt="avatar"> -->
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/x750ln/image/upload/v1586437668/user-circle_dlqni1.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% end %>
          <%#= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <%= current_user.username %>

          <!-- <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="paul.jpg"> -->
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%#= link_to "Votre compte", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>